### ISSUE TITLE
gmail email in support address?

### ISSUE THREAD

**Issue by sfkulyk** [diia-open-source/android-diia#1]
android-diia\notifications\src\main\res\layout\"

            tools:text="Для подробиць зателефонуйте  за номер \n+38 (000) 00 00 000 або напишіть на почту \nposhta@gmail.com. Детальна інструкція \nsupport.diia.gov.ua" />

I am not sure if this address is really in use, but a bit strange to use gmail mailbox for government application.
Also phone number is incorrect

**Comment by Quireg** [comment]
tools:text is used when you need to show sample data inside the layout for visual representation in AndroidStudio. This simplifies the development. Data is dummy. There is nothing strange about this.

**Comment by mrRomanko** [comment]
The only thing that is strange here is the word "почту" through the letter "ч" and not "ш"🤔 Why is the word in the orc language? 🤷‍♂️

**Comment by DiiaOpenSource** [comment]
Hi, @sfkulyk ! As stated above by @Quireg , these fake data are required for debugging and do not affect functionality. Therefore, we will close this defect as one that does not require editing. You can do it through the request pool if they are needed.
Thank you for being so passionate!
