### ISSUE TITLE
How to build a release version without deploying?

### ISSUE THREAD

**Issue by druidance** [diia-open-source/android-diia#30]
I didn't manage to build a release version of the app without deploying. There was no issues with `./gradlew :opensource:assembleGplayDebug` however. Tried `./gradlew :opensource:assembleGplayRelease`, but it didn't produce an .apk. Any suggestions on how to make it work?

**Comment by wert2all** [comment]
Maybe, should use  [bundle](https://developer.android.com/build/building-cmdline#build_bundle) and build bundle by `:opensource:bundleRelease`. Also, you could find a bundle on `opensource/build/outputs/bundle/gplayRelease` directory

**Comment by druidance** [comment]
Thank you for the proposed solution. What if there's no **Google Play** to install the bundle? 

I tried to use [bundletool](https://github.com/google/bundletool/releases) in order to convert **.aab** to **.apk**, and then, unpacked its contents. Now, it's a whole bunch of **base-*.apk** files inside. Which one to use for installation?

**Comment by drstranges** [comment]
> [bundletool](https://github.com/google/bundletool/releases) in order to convert **.aab** to **.apk**

Try to add `--mode=universal` to your `bundletool` command and then unzip the output apks file to find a `universal.apk`.

However, I'm pretty sure there should be a gradle command to generate the universal release apk.
