### ISSUE TITLE
Deprecated nginx version

### ISSUE THREAD

**Issue by ArchExalt** [diia-open-source/android-diia#5]
https://github.com/diia-open-source/android-diia/blob/017081e0e9852e680829a63892f4728762c1f3ca/ui_base/src/main/java/ua/gov/diia/ui_base/components/organism/carousel/HalvedCardCarouselOrg.kt#L63

The version of nginx on the website https://business.diia.gov.ua/uploads/ is 1.18.0, which reached the end of its security support on April 20, 2021.

UPD: nginx version is hidden but the issue must be still present though

**Comment by DiiaOpenSource** [comment]
@ArchExalt thank you. We have already fixed it :)

**Comment by ArchExalt** [comment]
You're welcome!
